# Generated by Django 5.1.3 on 2024-12-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_meeting_time_meetings_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='is_active',
            field=models.BooleanField(default='True'),
        ),
    ]
