# Generated by Django 5.1.3 on 2024-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_requests_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='date',
        ),
        migrations.AddField(
            model_name='meetings',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
