# Generated by Django 5.1.3 on 2024-12-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_availabletime_date_meetings_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='end_time',
            field=models.DateTimeField(default='2024-12-24 16:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='start_time',
            field=models.DateTimeField(default='2024-12-24 16:00:00'),
            preserve_default=False,
        ),
    ]
